Repository thamipontes/jogo, pull requests merged in 2021-06, with the labels that each got.

#27 Som da ponte caindo
  Assets/Resources/PONTE_DESMORONANDO_01.wav
  Assets/Resources/PONTE_DESMORONANDO_01.wav.meta
  Assets/Scripts/MusicManager.cs
  Assets/Scripts/Ponte.cs
Labels: Backend

#28 adiciona sons da caixa de diálogo: abrindo e fechando
  Assets/Resources/MENSAGEM_IN_01.wav
  Assets/Resources/MENSAGEM_IN_01.wav.meta
  Assets/Resources/MENSAGEM_OUT_01.wav
  Assets/Resources/MENSAGEM_OUT_01.wav.meta
  Assets/Scripts/Dialogo/Ana/DialogueManager.cs
  Assets/Scripts/MusicManager.cs
Labels: Backend, Prioridade da Semana

#29 conserta dano pena
  Assets/Scripts/PlayerHealth.cs
Labels: Backend

#35 Som do fundo no jogo
  Assets/Resources/SOM_DE-_FUNDO.wav
  Assets/Resources/SOM_DE-_FUNDO.wav.meta
  Assets/Scenes/Fase 1 - Ada/Ada Lovelace.unity
Labels: Backend

#39 Botões do menu
  Assets/Jogo/Interface/Opções/BOTÃO SAIR.png
  Assets/Jogo/Interface/Opções/Botão ativar diálogo.png
  Assets/Jogo/Interface/Opções/Botão ativar fundo musical.png
  Assets/Jogo/Interface/Opções/Botão ativar música.png
  Assets/Jogo/Interface/Opções/Botão desativar diálogo.png
  Assets/Jogo/Interface/Opções/Botão desativar fundo musical.png
  Assets/Jogo/Interface/Opções/Botão desativar música.png
  Assets/Jogo/Interface/Opções/Diálogo.png
  Assets/Jogo/Interface/Opções/Fundo de Opções.png
  Assets/Jogo/Interface/Opções/Música.png
  Assets/Jogo/Interface/Opções/Sons.png
Labels: Frontend
